---
# Nagios NRPE Server for Debian based OS's
- name: Install Nagios NRPE Server [Debian]
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
     - nagios-nrpe-server
     - libnagios-plugin-perl
